name: Run Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # TODO(xiyan): remove this once made public
    - name: Install dependencies
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
        pip install -e .

    - name: Run scripts
      env:
        LLAMA_API_KEY: ${{ secrets.LLAMA_API_KEY }}
      run: |
        python examples/chat.py
        python examples/async_chat.py
        python examples/vision.py
        python examples/structured.py
        python examples/tool_call.py